image: node:8

variables:
  STAGING_S3_BUCKET_NAME: "paperworkph-frontend-stg"
  PRODUCTION_S3_BUCKET_NAME: "paperworkph-frontend"

before_script:
  - apt-get update -qq

cache:
  paths:
  - node_modules/

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - echo "Installing dependencies"
    - yarn

lint:
  stage: test
  script:
    - echo "Running linter"
    - yarn lint

build_staging:
  stage: build
  script:
    - echo "Building the application"
    - yarn build:staging
  artifacts:
    paths:
      - build
  only:
    - staging

build_production:
  stage: build
  environment:
    name: production
  script:
    - echo "Building the application"
    - yarn build:production
  artifacts:
    paths:
      - build
  only:
    - master

deploy_staging:
  stage: deploy
  image: python:latest
  environment:
    name: staging
  before_script:
    - pip install awscli
  script:
    - echo "Deploy to staging server"
    - aws s3 sync build/ s3://$STAGING_S3_BUCKET_NAME
  artifacts:
    paths:
    - public
  only:
    - staging

deploy_production:
  stage: deploy
  image: python:latest
  environment:
    name: staging
  before_script:
    - pip install awscli
  script:
    - echo "Deploy to staging server"
    - aws s3 sync build/ s3://$PRODUCTION_S3_BUCKET_NAME
  artifacts:
    paths:
    - public
  only:
    - master
  when: manual
