image: docker:latest

services:
  - docker:dind

variables:
  REPOSITORY_URL: 660214559533.dkr.ecr.ap-southeast-1.amazonaws.com/paperworkph-api
  REGION: ap-southeast-1
  TASK_DEFINITION_NAME: microservices-task
  CLUSTER_NAME: paperworkph-cluster-1
  SERVICE_NAME: paperworkph-www

cache:
  paths:
  - node_modules/

stages:
  - install
  - test
  - build
  - deploy

install:
  image: node:8
  stage: install
  script:
    - echo "Installing dependencies"
    - yarn

lint:
  image: node:8
  stage: test
  script:
    - echo "Running linter"
    - yarn lint

build:
  stage: build
  only:
    - master
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region "${REGION}")
    - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"

    - echo "Building image..."
    - docker build -t $REPOSITORY_URL:latest -f Dockerfile.production .

    - echo "Tagging image..."
    - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG

    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:latest
    - docker push $REPOSITORY_URL:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region "${REGION}")
    - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"
  
    - echo $REPOSITORY_URL:$IMAGE_TAG
    - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "$TASK_DEFINITION_NAME" --region "${REGION}")
    - NEW_CONTAINER_DEFINITION=$(echo $TASK_DEFINITION | python $CI_PROJECT_DIR/update_task_definition_image.py $REPOSITORY_URL:$IMAGE_TAG)

    - echo "Registering new container definition..."
    - aws ecs register-task-definition --region "${REGION}" --family "${TASK_DEFINITION_NAME}" --container-definitions "${NEW_CONTAINER_DEFINITION}"

    - echo "Updating the service..."
    - aws ecs update-service --region "${REGION}" --cluster "${CLUSTER_NAME}" --service "${SERVICE_NAME}" --task-definition "${TASK_DEFINITION_NAME}"
  only:
    - master
