const CHECK = 'AuthConstants.CHECK';
const EMAIL_VERIFICATION = 'AuthConstants.EMAIL_VERIFICATION';
const EMAIL_VERIFICATION_PROCESSING = 'AuthConstants.EMAIL_VERIFICATION_PROCESSING';
const LOGIN = 'AuthConstants.LOGIN';
const LOGOUT = 'AuthConstants.LOGOUT';
const REGISTER = 'AuthConstants.REGISTER';
const FORGOT_PASSWORD = 'AuthConstants.FORGOT_PASSWORD';
const FORGOT_PASSWORD_PROCESSING = 'AuthConstants.FORGOT_PASSWORD_PROCESSING';

export default {
  CHECK,
  EMAIL_VERIFICATION,
  EMAIL_VERIFICATION_PROCESSING,
  LOGIN,
  LOGOUT,
  REGISTER,
  FORGOT_PASSWORD,
  FORGOT_PASSWORD_PROCESSING,
};
