version: '3'

services:
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperworkph-db
      POSTGRES_USER: paperworkph-db-user
      POSTGRES_PASSWORD: password

  db-cli:
    build: ./../../microservices/db-cli
    image: db-cli:1.0.0
    depends_on:
      - db
    volumes:
      - ./../../microservices/db-cli:/app:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  api:
    build: ./../../microservices/api
    image: api:1.0.0
    links:
      - db-cli
      - emailer
    volumes:
      - ./../../microservices/api:/app:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  emailer:
    build: ./../../microservices/emailer
    image: emailer:1.0.0
    links:
      - db-cli
      - db
    volumes:
      - ./../../microservices/emailer:/app:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1080/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  admin:
    build: ./../../microservices/admin
    image: admin:1.0.0
    depends_on:
      - api
    ports:
      - "4000:4000"
    volumes:
      - ./../../microservices/admin:/app:rw

  frontend:
    build: ./../../microservices/frontend
    image: frontend:1.0.0
    depends_on:
      - api
    ports:
      - "80:3000"
    volumes:
      - ./../../microservices/frontend:/app:rw

  barcode:
    build: ./../../microservices/barcode
    image: barcode:1.0.0
    ports:
      - "6543:6543"
    volumes:
      - ./../../microservices/barcode:/code

volumes:
  db-data:
